### ISSUE TITLE
No module found

### ISSUE THREAD

**Issue by bcritt1** [blueprintparadise/booknlp2#2]
Running the sample code in conda results in the following error:

`(booknlp2) user@wheat-01:~$ python booknlp.py
Traceback (most recent call last):
  File "booknlp.py", line 1, in <module>
    from booknlp.booknlp import BookNLP
  File "/home/users/$USER/booknlp.py", line 1, in <module>
    from booknlp.booknlp import BookNLP
ModuleNotFoundError: No module named 'booknlp.booknlp'; 'booknlp' is not a package`

It is installed in the environment:
`(booknlp2) user@rice-04:~$ conda list
# packages in environment at /home/users/$USER/.conda/envs/booknlp2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   2.1.0                    pypi_0    pypi
annotated-types           0.5.0                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
blis                      0.7.11                   pypi_0    pypi
booknlp2                  1.0.3                    pypi_0    pypi`

Had this issue also with David's version, which makes me think it might be an OS/environment issue (Ubuntu 22.04.4 LTS (GNU/Linux 6.5.0-41-generic x86_64)). Thanks!

**Comment by blueprintparadise** [comment]
Thank you for reporting this issue. I am working on adding direct Multi OS pip install support in the next few days.

Regards,
Blueprintparadise
